input_path = "Test0006.ks2"
output_dir = "out"
output_file_name = "result.csv"
auto_detect_offsets = true

header_byte = 256
variable_header_byte = 2890 
data_header_byte = 13452 
data_skip_byte = 12
footer_byte = 28

# 1レコード = 4 * i32 = 16 byte
values_per_record = 4

# i32 のエンディアン
endianness = "little"

ADConverterScale = 2099200002
ADRangeCoefficient = 5000
ADCoefficient = 256

[coefficient]
CH1 = 1.05
CH2 = 1.13
CH3 = 1.04
CH4 = 1.12
